baseURL = "/"
languageCode = "en-us"
title = "Valutatori Sociali"
theme = "strange-case"

[params.sidebar]
  enable = true

[params.widgets]
header = ["breadcrumbs"]
homepage = ["recent_posts"]
sidebar = ["about","search","sidebar_menu","taxonomy_cloud"]
footer = ["social_menu"]

