baseURL = "/"
languageCode = "en-us"
title = "Valutatori Sociali"
theme = "mytheme"
[staticman]
  endpoint = "https://api.staticman.net/v2/entry/"
  username = "mauromussin"
  repository = "valutatorisociali"
  branch = "master"

[params.sidebar]
  enable = true

[params.widgets]
header = ["breadcrumbs"]
homepage = ["recent_posts"]
sidebar = ["about","search","sidebar_menu","taxonomy_cloud"]
footer = ["social_menu"]

